# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project Alpha
email: projectalpha@seedplus.com
description: > # this means to ignore newlines until "baseurl:"
  Powering the next breakout story in South East Asia, by AWS and SeedPlus
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alpha.seedplus.com" # the base hostname & protocol for your site
linkedin-url: "https://www.linkedin.com/company/seedplus"
twitter-url: "https://twitter.com/seedplusvc"

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
  events:
    output: false
